package insert

import (
	"context"
	"encoding/hex"
	"fmt"
	"io"
	"strconv"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/mickamy/seeder/internal/introspect"
)

// sqlOutputDriver writes INSERT (and optional TRUNCATE) statements to an
// io.Writer instead of executing them. dialect ("mysql" / "postgres" /
// "postgresql") selects literal escaping and identifier quoting. Inserted
// rows are retained in-memory so FK / polymorphic pools downstream can pick
// from them (mirrors what Driver.ColumnValues does against a real DB).
// identityTables tracks which tables carry an IDENTITY column so the
// Postgres dialect can emit OVERRIDING SYSTEM VALUE on those INSERTs.
type sqlOutputDriver struct {
	w              io.Writer
	dialect        string
	written        map[string][]map[string]any
	identityTables map[string]bool
}

func newSQLOutputDriver(w io.Writer, dialect string, schema introspect.Schema) *sqlOutputDriver {
	identityTables := make(map[string]bool)
	for _, t := range schema.Tables {
		for _, c := range t.Columns {
			if c.IsIdentity {
				identityTables[t.Name] = true

				break
			}
		}
	}

	return &sqlOutputDriver{
		w:              w,
		dialect:        dialect,
		written:        make(map[string][]map[string]any),
		identityTables: identityTables,
	}
}

func (d *sqlOutputDriver) Close(_ context.Context) error { return nil }

func (d *sqlOutputDriver) Truncate(_ context.Context, tables []string) error {
	if len(tables) == 0 {
		return nil
	}
	for _, t := range tables {
		switch d.dialect {
		case "mysql":
			if _, err := fmt.Fprintf(d.w, "TRUNCATE TABLE %s;\n", quoteMySQLIdent(t)); err != nil {
				return fmt.Errorf("write truncate: %w", err)
			}
		default:
			if _, err := fmt.Fprintf(d.w, "TRUNCATE %s RESTART IDENTITY CASCADE;\n", pgx.Identifier{t}.Sanitize()); err != nil {
				return fmt.Errorf("write truncate: %w", err)
			}
		}
	}

	return nil
}

func (d *sqlOutputDriver) BulkInsert(_ context.Context, table string, columns []string, rows [][]any) (int64, error) {
	if len(rows) == 0 {
		return 0, nil
	}

	quoteIdent := func(s string) string { return pgx.Identifier{s}.Sanitize() }
	if d.dialect == "mysql" {
		quoteIdent = quoteMySQLIdent
	}

	quoted := make([]string, len(columns))
	for i, c := range columns {
		quoted[i] = quoteIdent(c)
	}
	overriding := ""
	if d.dialect != "mysql" && d.identityTables[table] {
		// GENERATED ALWAYS AS IDENTITY rejects explicit values without this
		// clause; GENERATED BY DEFAULT silently accepts it.
		overriding = " OVERRIDING SYSTEM VALUE"
	}
	header := fmt.Sprintf("INSERT INTO %s (%s)%s VALUES\n", quoteIdent(table), strings.Join(quoted, ", "), overriding)
	if _, err := d.w.Write([]byte(header)); err != nil {
		return 0, fmt.Errorf("write header: %w", err)
	}
	for i, row := range rows {
		vals := make([]string, len(row))
		for j, v := range row {
			vals[j] = sqlLiteral(v, d.dialect)
		}
		sep := ","
		if i == len(rows)-1 {
			sep = ";"
		}
		if _, err := fmt.Fprintf(d.w, "  (%s)%s\n", strings.Join(vals, ", "), sep); err != nil {
			return 0, fmt.Errorf("write row: %w", err)
		}
	}

	d.written[table] = appendBoundedRows(d.written[table], columns, rows, defaultPoolCapacity)

	return int64(len(rows)), nil
}

func (d *sqlOutputDriver) ColumnValues(_ context.Context, table string, columns []string) (map[string][]any, error) {
	out := make(map[string][]any, len(columns))
	for _, row := range d.written[table] {
		for _, c := range columns {
			out[c] = append(out[c], row[c])
		}
	}

	return out, nil
}

func sqlLiteral(v any, dialect string) string {
	if v == nil {
		return "NULL"
	}
	switch x := v.(type) {
	case string:
		if dialect == "mysql" {
			return "'" + mysqlEscapeString(x) + "'"
		}
		return "'" + strings.ReplaceAll(x, "'", "''") + "'"
	case bool:
		if dialect == "mysql" {
			if x {
				return "1"
			}
			return "0"
		}
		if x {
			return "TRUE"
		}
		return "FALSE"
	case int:
		return strconv.Itoa(x)
	case int8:
		return strconv.Itoa(int(x))
	case int16:
		return strconv.Itoa(int(x))
	case int32:
		return strconv.Itoa(int(x))
	case int64:
		return strconv.FormatInt(x, 10)
	case uint:
		return strconv.FormatUint(uint64(x), 10)
	case uint8:
		return strconv.FormatUint(uint64(x), 10)
	case uint16:
		return strconv.FormatUint(uint64(x), 10)
	case uint32:
		return strconv.FormatUint(uint64(x), 10)
	case uint64:
		return strconv.FormatUint(x, 10)
	case float32:
		return strconv.FormatFloat(float64(x), 'g', -1, 32)
	case float64:
		return strconv.FormatFloat(x, 'g', -1, 64)
	case time.Time:
		if dialect == "mysql" {
			// MySQL DATETIME / TIMESTAMP literals have no zone; the server
			// applies time_zone to the value at insert time.
			return "'" + x.UTC().Format("2006-01-02 15:04:05.999999") + "'"
		}
		// Postgres accepts ISO 8601 with offset; emit an unambiguous UTC instant.
		return "'" + x.UTC().Format(time.RFC3339Nano) + "'"
	case []byte:
		if dialect == "mysql" {
			return "X'" + hex.EncodeToString(x) + "'"
		}
		// Postgres bytea hex escape: '\x...'
		return `'\x` + hex.EncodeToString(x) + `'`
	}

	return "'" + strings.ReplaceAll(fmt.Sprintf("%v", v), "'", "''") + "'"
}

// appendBoundedRows is the shared helper that output drivers use to retain
// inserted rows in-memory (so FK / polymorphic pickers can read them back
// via ColumnValues). It tail-trims to capacity, mirroring Pool's policy so
// long output runs stay memory-bounded.
func appendBoundedRows(
	existing []map[string]any,
	columns []string,
	rows [][]any,
	capacity int,
) []map[string]any {
	for _, row := range rows {
		m := make(map[string]any, len(columns))
		for i, c := range columns {
			m[c] = row[i]
		}
		existing = append(existing, m)
	}
	if capacity > 0 && len(existing) > capacity {
		existing = existing[len(existing)-capacity:]
	}

	return existing
}

// mysqlEscapeString applies MySQL string-literal escaping. ANSI_QUOTES /
// NO_BACKSLASH_ESCAPES are not assumed; escape backslashes and the special
// control bytes the server interprets unless that mode is set.
func mysqlEscapeString(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for i := range len(s) {
		switch s[i] {
		case 0:
			b.WriteString(`\0`)
		case '\b':
			b.WriteString(`\b`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		case 0x1A:
			b.WriteString(`\Z`)
		case '\'':
			b.WriteString(`\'`)
		case '\\':
			b.WriteString(`\\`)
		default:
			b.WriteByte(s[i])
		}
	}

	return b.String()
}
